### ISSUE TITLE
Supported engines: npm

### ISSUE THREAD

**Issue by cmmdmx** [use-cookie-consent/use-cookie-consent#20]
**Describe the bug**
Package "core" does not support npm?

**To Reproduce**
1. Install core or react package
2. Get following message from npm:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@use-cookie-consent/core@0.3.3',
npm WARN EBADENGINE   required: { node: '>=12', npm: '<0', yarn: '^1' },
npm WARN EBADENGINE   current: { node: 'v14.18.1', npm: '8.1.1' }
npm WARN EBADENGINE }
```

**Expected behavior**
No message like this

**Desktop (please complete the following information):**
 - OS:  WSL on Windows 10

**Additional context**
Is there a reason for saying npm <0? Otherwise it seems to be easy to fix ;)

**Comment by bring-shrubbery** [comment]
Yeah, the idea here is that you should use Yarn instead since we use `yarn.lock` file. Maybe it is an unnecessary precaution though, what do you think?

**Comment by cmmdmx** [comment]
Thx for your fast reply!

I'd say following: For developing the package, it's your choice to say if it should be yarn or npm, for sure!
But as a consumer of the library it shouldn't be restricted.
Correct me if I'm wrong, but the lock files (either yarn or npm) are only relevant during development, not during consuming the final library?

I expect there is a solution to exclude the `engines.npm` and `engines.yarn` part of the `package.json` from the published package during build process.

**Comment by bring-shrubbery** [comment]
@cmmdmx hey, thanks for reply.

I think I agree woth you that we don't need to restrict these. Although they are good to have even in development (so that you don't have random version change in a dependency of a dependency) there's no need to restrict to use just one, since the CI will always use yarn and use the yarn lock file. I can just exclude the package-lock fron git, and no harm done - worst case scenario is that CI wont pass!

**Comment by cmmdmx** [comment]
Excluding package-lock via git seems to be perfectly fine 👍

**Comment by bring-shrubbery** [comment]
@cmmdmx I fixed the issue, you should be able to use npm if you want!

**Comment by max-crcl** [comment]
Looks like the warning is gone, thank you!

**Comment by cmmdmx** [comment]
Looks like the warning is gone, thank you!
