### ISSUE TITLE
Add Cypress tests

### ISSUE THREAD

**Issue by Stalkakuma** [use-cookie-consent/use-cookie-consent#31]
I want to check if Cookies are set correctly.

So far I have tried various Jest mocks, but could not get the results I expected.

**Comment by bring-shrubbery** [comment]
@Stalkakuma You should use the issue templates, in this case you should have used "Feature Request" template

**Comment by Stalkakuma** [comment]
> @Stalkakuma You should use the issue templates, in this case you should have used "Feature Request" template

I did! I just deleted the template itself...

**Comment by bring-shrubbery** [comment]
> > @Stalkakuma You should use the issue templates, in this case you should have used "Feature Request" template
> 
> I did! I just deleted the template itself...

The lines that are bold should stay in that case
